name: CI/CD Pipeline - Build and Deploy to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: project-3a1d8bf1-cfc1-4a30-bdb
  REGION: us-central1
  CLUSTER_NAME: devops-cluster
  CLUSTER_ZONE: us-central1-a
  REGISTRY: us-central1-docker.pkg.dev
  IMAGE_NAME: devops-app

permissions:
  contents: read
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Run linter
        working-directory: ./app
        run: echo "Lint passed"

  containerize-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/303806623199/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@project-3a1d8bf1-cfc1-4a30-bdb.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build Docker image
        working-directory: ./app
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Deploy to GKE
        run: |
          sed -i "s|us-central1-docker.pkg.dev/project-3a1d8bf1-cfc1-4a30-bdb/devops-app/devops-app:latest|${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl scale deployment devops-app --replicas=0
          kubectl scale deployment devops-app --replicas=3

      - name: Verify deployment
        run: |
          sleep 30
          kubectl get pods
          kubectl get svc
